name: Build and Sign Android APK

on:
  push:
    tags:
      - 'Version*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename Signed APK
        run: |
          mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/abonar-${{ github.ref_name }}.apk
          echo "APK_PATH=app/build/outputs/apk/release/abonar-${{ github.ref_name }}.apk" >> $GITHUB_ENV

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: abonar-${{ github.ref_name }}
          path: ${{ env.APK_PATH }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: latest
          name: "Latest Releases"
          files: ${{ env.APK_PATH }}
          body: "Historial de versiones compiladas. La versión más reciente añadida es: ${{ github.ref_name }}"
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
